## Name: Krina Bharatbhai Patel
## Net Id : vj3004

## Name: Fnu,Sharmila Bolikoppa Palakshappa
## Net Id : bm6575

## Name: Vatsal Sudhir Pathak
## Net Id : pv2556

## Group Id: 7
## Assignment 2

## Q1 [3pts]: Parametric Classification: Using each of the 64 input features separately as the single input dimension, use parametric classification, assuming that the input is distributed according to a Gaussian. Report the training and test errors for the case of each of the 64 features. Which feature(s) give the best test performance?

In [3]:
import numpy as np
from pandas import DataFrame, read_csv, to_numeric
from sklearn import cluster
import pandas as pd
from numpy.linalg import multi_dot

df_train = read_csv('optdigits_69_N200.tra',header=None)
df_test = read_csv('optdigits_69.tes',header=None)

In [4]:
# computing variance for each columns for each class
# if variance is below or equal to 0(var_threshold) for any column for any class, that column will be dropped

var_threshold = 0
df_var = df_train.groupby(by=64).var()
s_var_threshold = (df_var > var_threshold).product()
columns_to_drop = s_var_threshold[s_var_threshold == 0].index

In [5]:
columns_to_drop

Int64Index([0, 1, 6, 7, 8, 14, 15, 16, 21, 22, 23, 24, 31, 32, 39, 40, 47, 48,
            56],
           dtype='int64')

In [6]:
# drop columns with variance below or equal to  threshold
df_train = df_train.drop(columns = columns_to_drop)
df_test = df_test.drop(columns = columns_to_drop)

## Find statistics (mean, covariance and probability) for each label (6,9)

In [7]:
#computing the estimates

m = df_train.groupby(by=64).mean()
s = df_train.groupby(by=64).std()
count = df_train.groupby(by=64).count()
prob = count / count.sum()

## Linear Discriminant Function

In [8]:
# g_i(x) for i = 1, 2 i.e, two discirminant function for class 6 and 9

def discriminant_predict(x):
    g = -0.5 * np.log(2*np.pi) - np.log(s) - ((x - m) **2)/(2*(s**2)) + np.log(prob)
    return g.idxmax()

## Predict Function

In [9]:
#computing discriminant function for training set

df_train_no_label = df_train.drop(columns=[64])

results = []
for i in range(df_train_no_label.shape[0]):
    x = df_train_no_label.iloc[i]
    res = discriminant_predict(x)
    results.append(res)

In [10]:
df_results = pd.DataFrame(results)

## Find train and test errors

In [11]:
#Training Error
s1 = df_results.ne(df_train[64], axis=0).mean().sort_values()*100

In [12]:
#computing discriminant function for testing set

df_test_no_label = df_test.drop(columns=[64])

results_test = []
for i in range(df_test_no_label.shape[0]):
    x_test = df_test_no_label.iloc[i]
    res_test = discriminant_predict(x_test)
    results_test.append(res_test)

In [13]:
# Testing error calculation

df_results_test = pd.DataFrame(results_test)
s2=df_results_test.ne(df_test[64], axis=0).mean().sort_values()*100

## Displaying training and testing error for each feature in ascending order

In [16]:
df_final = pd.concat([s1, s2], axis=1)
df_final.columns=["Train_error","Test_error"]    
df_final.sort_values("Test_error")

    Train_error  Test_error
42          0.5    1.108033
13          8.0    7.202216
29          2.0    8.033241
34          9.5    8.310249
43          9.5    9.141274
30          9.5   13.296399
20         18.5   14.958449
28         15.5   15.789474
51         20.0   16.620499
33         26.0   19.390582
35         25.5   20.498615
2          31.5   22.160665
10         29.5   22.437673
58         31.0   22.991690
41         28.5   23.268698
11         39.0   23.545706
36         29.0   24.930748
9          31.0   25.761773
54         17.5   26.592798
50         22.5   27.977839
17         27.5   29.916898
5          31.5   30.193906
61         26.0   31.024931
27         37.0   32.963989
59         26.5   33.240997
26         39.0   34.349030
46         27.0   34.349030
12         29.0   34.903047
19         38.5   35.734072
62         25.0   36.842105
38         36.0   37.119114
44         44.5   37.673130
3          32.5   37.673130
60         36.0   40.720222
4          34.0   42.105263
37         37.0   45.152355
49         49.0   45.152355
55         40.0   45.152355
52         37.0   45.983380
57         46.5   45.983380
53         53.5   47.645429
63         44.0   49.307479
45         45.0   51.246537
18         45.5   51.523546
25         47.0   54.570637

## From the above table the 10 features giving the best test performance are:

In [17]:
df_final.sort_values("Test_error").head(10)

    Train_error  Test_error
42          0.5    1.108033
13          8.0    7.202216
29          2.0    8.033241
34          9.5    8.310249
43          9.5    9.141274
30          9.5   13.296399
20         18.5   14.958449
28         15.5   15.789474
51         20.0   16.620499
33         26.0   19.390582